apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  name: default
backupStorageProvider:
  name: aws
  bucket: my-cluster-backup
  resticLocation: my-volumes-backup
  config:
    region: eu-west-1
backupSyncPeriod: 60m
gcSyncPeriod: 60m
scheduleSyncPeriod: 5m
restoreOnlyMode: false
---
apiVersion: ark.heptio.com/v1
kind: Schedule
metadata:
  name: cluster-only
spec:
  schedule: "*/30 * * * *"
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    ttl: 72h0m0s
