apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restic
spec:
  template:
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: ark
        envFrom:
        - secretRef:
            name: cloud-credentials
