apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark
spec:
  replicas: 1
  selector:
      matchLabels:
          app: ark
  template:
    metadata:
      labels:
        app: ark
    spec:
      restartPolicy: Always
      serviceAccountName: ark
      containers:
        - name: ark
          image: gcr.io/heptio-images/ark:v0.9.10
          command:
            - /ark
          args:
            - server
          ports:
            - name: metrics
              containerPort: 8085
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: plugins
              mountPath: /plugins
            - name: scratch
              mountPath: /scratch
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: ARK_SCRATCH_DIR
              value: /scratch
      volumes:
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ark
  labels:
    app: ark
spec:
  ports:
  - port: 8085
    protocol: TCP
    name: metrics
  selector:
    app: ark
