# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

namespace: kube-system

bases:
  - ../velero-base

images:
  - name: velero/velero-plugin-for-gcp
    newName: registry.sighup.io/fury/velero/velero-plugin-for-gcp
    newTag: v1.1.0

patchesStrategicMerge:
  - plugin-patch.yaml
