apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restic
  labels:
    app: restic
spec:
  selector:
    matchLabels:
      app: restic
  template:
    metadata:
      labels:
        app: restic
    spec:
      serviceAccountName: ark
      securityContext:
        runAsUser: 0
      containers:
      - name: ark
        image: gcr.io/heptio-images/ark:v0.10.1
        command:
        - /ark
        args:
        - restic
        - server
        volumeMounts:
        - name: host-pods
          mountPath: /host_pods
          mountPropagation: HostToContainer
        - name: scratch
          mountPath: /scratch
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HEPTIO_ARK_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ARK_SCRATCH_DIR
          value: /scratch
      volumes:
      - name: host-pods
        hostPath:
          path: /var/lib/kubelet/pods
      - name: scratch
        emptyDir: {}
