apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: full
spec:
  schedule: "0 1 * * *"
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: true
    includedNamespaces:
    - '*'
    includedResources:
    - '*'
    labelSelector: null
    storageLocation: default
    ttl: 720h0m0s
    volumeSnapshotLocations:
    - default
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: manifests
spec:
  schedule: "*/15 * * * *"
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: true
    snapshotVolumes: false
    includedNamespaces:
    - '*'
    includedResources:
    - '*'
    labelSelector: null
    storageLocation: default
    ttl: 720h0m0s
    volumeSnapshotLocations:
    - default
